extends Resource
class_name AreaBeneathCurve
## Contains the polygon as a list of [PackedVector2Array] and
## the signed area as a [float]
##
## Is generated by the [PlotItem] when [methode PlotItem _redraw]
## is called. This resource represents the area contained between
## the curve and the x-axis, AKA the integral of the curve.
## It contains the polygon as a [PackedVector2Array] and the signed
## area (i.e. a negative value for areas under the x-axis) as 
## a [float]. [br]
## A new [AreaBeneathCurve] is generated at each switch of sign of
## the curve, so the polygon is not auto intersecting.

var points : PackedVector2Array
var area : float
